---
abstract: 'RT-Extension-CustomiseMenus Extension'
author:
  - 'Martin Wheldon <martin.wheldon@greenhills-it.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.17'
license: gplv2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-CustomiseMenus
no_index:
  directory:
    - html
    - inc
    - xt
requires:
  perl: 5.10.1
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: https://github.com/wheldom01/rt-extension-customisemenus
version: '0.01'
x_module_install_rtx_version: '0.38'
x_requires_rt: 4.4.0
x_rt_too_new: 4.6.0
